CREATE DATABASE LIVRARIA;

CREATE TABLE AUTOR
(
    COD INT PRIMARY KEY AUTO_INCREMENT NOT NULL,
    NOME VARCHAR(255) NOT NULL,
    COD_AUTOR INT NOT NULL
)ENGINE=INNODB;

CREATE TABLE LIVROS_AUTOR
(
    COD INT PRIMARY KEY AUTO_INCREMENT NOT NULL,
    COD_AUTOR INT NOT NULL,
    COD_LIVRO INT NOT NULL
)ENGINE=INNODB;

CREATE TABLE LIVRO
(
    COD INT PRIMARY KEY AUTO_INCREMENT NOT NULL,
    TITULO VARCHAR(255) NOT NULL,
    COD_LIVRO INT NOT NULL,
    IDIOMA VARCHAR(55) NOT NULL,
    EDICAO VARCHAR(55) NOT NULL,
    FORMATO VARCHAR(55) NOT NULL,
    DATA_PUBLICACAO DATE NOT NULL,
    NUMERO_PAGINAS INT NOT NULL,
    VALOR DECIMAL(4,6) NOT NULL,
    QUANTIDADE INT NOT NULL,
    DESCRICAO TEXT NOT NULL,
    CAPA TEXT NOT NULL
)ENGINE=INNODB;


ALTER TABLE AUTOR ADD FOREIGN KEY (COD_AUTOR) REFERENCES LIVROS_AUTOR (COD_AUTOR);

ALTER TABLE LIVRO ADD FOREIGN KEY (COD_LIVRO) REFERENCES LIVROS_AUTOR (COD_LIVRO);

